version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ../../data/infra/grafana/data:/var/lib/grafana
      - ../../data/infra/grafana/log:/var/log/grafana

  influxdb:
    image: influxdb:1.8.10
    restart: unless-stopped
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_USER: k6
      INFLUXDB_USER_PASSWORD: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    volumes:
      - ../../data/infra/influxdb/data:/var/lib/influxdb
      - ../../data/infra/influxdb/config:/etc/influxdb