version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ../../data/mysql/:/var/lib/mysql
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    command:
      - --mysqld.username=root
      - --mysqld.address=mysql:3306
    environment:
      - MYSQLD_EXPORTER_PASSWORD=root
    depends_on:
      - mysql